// <auto-generated />
using System;
using EventsApi.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EventsApi.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220708214328_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EventsApi.Domain.Entities.EventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EventPlace")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organizer")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Plan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Speaker")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Talk about animals.",
                            EventPlace = "Mogilev",
                            EventTime = new DateTime(2022, 7, 9, 0, 43, 27, 712, DateTimeKind.Local).AddTicks(4880),
                            Name = "Nature",
                            Organizer = "Samuliou Stsiapan",
                            Plan = "1. Start; 2. Talk; 3. End;",
                            Speaker = "Byarozkin Hleb"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Talk about sport.",
                            EventPlace = "Minsk",
                            EventTime = new DateTime(2022, 7, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Sport",
                            Organizer = "Lionel Messi",
                            Plan = "1. Start; 2. Talk; 3. End;",
                            Speaker = "Cristiano Ronaldo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
